### ISSUE TITLE
Regarding camera

### ISSUE THREAD

**Issue by karthikbnd** [lukagabric/PyALPR#1]
In this code which camera is used usb or raspberry pi camera

**Comment by karthikbnd** [comment]
$ sudo python PyALPR.py
Traceback (most recent call last):
  File "PyALPR.py", line 64, in <module>
    plate_reader.read_plate()
  File "PyALPR.py", line 40, in read_plate
    alpr_json, alpr_error = self.alpr_json_results()
  File "PyALPR.py", line 25, in alpr_json_results
    self.webcam_subprocess().communicate()
  File "PyALPR.py", line 17, in webcam_subprocess
    return subprocess.Popen(self.webcam_command_args, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by JesseXia** [comment]
I'm getting this error as well, have any idea about this?

**Comment by datomnurdin** [comment]
I also got this error message.

**Comment by mehuaniket** [comment]
I'm also getting this message!!

**Comment by tirthrajchauhan** [comment]
I also get this same error.

**Comment by ihalili** [comment]
Please Install this
sudo apt-get install fswebcam
